main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('my_home/', views.my_home, name='my_home'),
    path('create/', views.create, name='create'),
    path('edit/<int:recipe_id>/', views.edit, name='edit'),
    path('<int:recipe_id>/', views.recipe, name='recipe')
]

recipe_database/urls.py
from django.contrib import admin
from django.urls import path, include
from user_registration import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', views.register, name='register'),
    path('', include("django.contrib.auth.urls"))
]

recipie_database/urls.py
from django.contrib import admin
from django.urls import path, include
from user_registration import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('register/', views.register, name='register'),
    path('', include("django.contrib.auth.urls"))
]

main/models.py
from pyexpat import model
from tabnanny import verbose
from django.db import models

# Create your models here.
class Diet(models.Model):
    diet = models.CharField('diet', max_length=100, unique=True, blank=True)

    def __str__(self):
        return self.diet

class Cuisine(models.Model):
    cuisine = models.CharField('cuisine', max_length=100, unique=True, blank=True)

    def __str__(self):
        return self.cuisine

class Difficulty(models.Model):
    DIFFICULTIES = (
    ('EASY', 'Beginner'),
    ('MEDIUM', 'Intermediate'),
    ('HARD', 'Advanced')
    )
    difficulty = models.CharField('difficulty', max_length=100, choices=DIFFICULTIES)

    def __str__(self):
        return self.difficulty

    class Meta:
        verbose_name = 'difficulty'
        verbose_name_plural = 'difficulties'


class CookTime(models.Model):
    COOK_TIMES = (
    ('SHORTEST', '0min - 30min'),
    ('SHORT', '30min - 1hr'),
    ('LONG', '1hr - 2hr'),
    ('LONGEST', '2hr +')
    )
    cook_time = models.CharField('cook time', max_length=100, choices=COOK_TIMES)

    def __str__(self):
        return self.cook_time

class Ingredient(models.Model):
    ingredient_name = models.CharField('ingredient', max_length=100, unique=True)

    def __str__(self):
        return self.ingredient_name

class PrepMethod(models.Model):
    prep_method = models.CharField('prep method', max_length=100, unique=True)

    def __str__(self):
        return self.prep_method

class QuantityUnit(models.Model):
    quantity_unit = models.CharField('quantity unit', max_length=100, unique=True)

    def __str__(self):
        return self.quantity_unit

class Recipe(models.Model):
    recipe_name = models.CharField('recipe name', max_length=100)
    description = models.TextField('description', max_length=200)
    instructions = models.TextField('instructions', max_length=800)
    diet = models.ManyToManyField(Diet, blank=True)
    cuisine = models.ForeignKey(
        'Cuisine', 
        on_delete=models.CASCADE, 
        related_name='recipes', 
        related_query_name='recipe',
        blank=True
        )
    difficulty = models.ForeignKey(
        'Difficulty', 
        on_delete=models.CASCADE,
        related_name='recipes',
        related_query_name='recipe'
        )
    cook_time = models.ForeignKey(
        'CookTime', 
        on_delete=models.CASCADE,
        related_name='recipes',
        related_query_name='recipe'
        )

    def __str__(self):
        return self.recipe_name


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(
        'Recipe', 
        on_delete=models.CASCADE,
        related_name='recipe_ingredients',
        related_query_name='recipe_ingredient'
        )
    ingredient = models.ForeignKey(
        'Ingredient', 
        on_delete=models.CASCADE,
        related_name='recipe_ingredients',
        related_query_name='recipe_ingredient'
        ) 
    quantity_unit = models.ForeignKey(
        'QuantityUnit', 
        on_delete=models.CASCADE,
        related_name='recipe_ingredients',
        related_query_name='recipe_ingredient'
        )
    prep_method = models.ForeignKey(
        'PrepMethod', 
        on_delete=models.CASCADE,
        related_name='recipe_ingredients',
        related_query_name='recipe_ingredient',
        blank=True
        )
    amount = models.FloatField()

    def __str__(self):
        return self.ingredient

main/forms.py
from django.forms import BaseInlineFormSet, ChoiceField, ModelForm, inlineformset_factory 
from .models import Diet, Cuisine, Difficulty, CookTime, Ingredient, PrepMethod, QuantityUnit, Recipe, RecipeIngredient 

class CustomInlineIngredientFormset(BaseInlineFormSet):
    def clean(self):
        for form in self.forms:
            ingredient = form.cleaned_data['ingredient']
            quantity_unit = form.cleaned_data['quantity_unit']
            prep_method = form.cleaned_data['prep_method']
            if ingredient not in Ingredient.objects.all():
                new_ingredient = Ingredient(ingredient_name=ingredient)
                new_ingredient.save()
                form.cleaned_data['ingredient'] = new_ingredient.id
                form.instance.ingredient = new_ingredient.id
        super().clean()


class CreateNewRecipe(ModelForm):
    difficulty = ChoiceField(choices=Difficulty.DIFFICULTIES)
    cook_time = ChoiceField(choices=CookTime.COOK_TIMES)
    
    class Meta:
        model = Recipe
        fields = '__all__'

IngredientFormSet = inlineformset_factory(
    Recipe,
    RecipeIngredient,
    exclude=('recipe',),
    extra=1,
    formset=CustomInlineIngredientFormset
)

main/views.py
from re import search
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from requests import request
from .models import Diet, Cuisine, Difficulty, CookTime, Ingredient, PrepMethod, QuantityUnit, Recipe, RecipeIngredient 
from .forms import CreateNewRecipe, IngredientFormSet

# Create your views here.
# main home page
# show 3 random recipes
# search bar
# login link
# if user signed in, show user home page link
def home(response): 
    return render(response, 'main/home.html', {})

# user home page
# show list of created repicies
# buttons to delete or edit
# if no one signed in, show sign in link
def my_home(response): 
    return render(response, 'main/user_home.html', {})

# create new recipe page
# show recipe form
def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def create(response):
    if is_ajax(response):
        term = response.GET.get('term')
        ingredients = Ingredient.objects.all().filter(ingredient_name__icontains=term)
        response_content = list(ingredients.values())
        return JsonResponse(response_content, safe=False)
    elif response.method == 'POST':
        form_data = dict(response.POST)
        recipe_data = {}
        ingredient_data = {}
        for item, value in form_data.items():
            if item == 'csrfmiddlewaretoken' or item == 'save':
                pass
            elif item.startswith('recipe_ingredients'):
                ingredient_data[item] = value
            else:
                recipe_data[item] = value
        print(recipe_data)
        print(ingredient_data)
        formset_data = {}
        counter = 0
        # setting counter to match number of forms created in set during loop
        # access correct form data by matching count number to form id number
        for item, value in ingredient_data.items():
            if search('.\-' + str(counter) + '\\-.', item):
                formset_data[item] = value
            else:
                new_ingredient = RecipeIngredient(formset_data)
                new_ingredient.save()
                formset_data.clear()
            counter += 1
        new_recipe = Recipe(recipe_data)
        print(new_recipe)
        new_recipe.save()
                
        
        return HttpResponseRedirect(reverse('home'))
    else:
        recipe_form = CreateNewRecipe()
        ingredient_formset = IngredientFormSet(queryset=RecipeIngredient.objects.none())

        
    return render(
        response, 
        'main/create.html', 
        {'recipe_form': recipe_form, 'ingredient_formset': ingredient_formset}
        )

# edit recipe page
# show edit form populated with currect recipe data
def edit(response, id): 
    return render(response, 'main/edit.html', {})

# recipe page
# show recipe information
# add button to show random recipe
def recipe(response, id):
    return render(response, 'main/recipe_page.html', {})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        Base
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css">
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #214a1a">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                    <a class="nav-link" href="{% url 'create' %}">Create New Recipe</a>
                </div>
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'my_home' %}">Profile</a>
                        <a class="nav-link" href="{% url 'logout' %}"><i class="bi bi-door-closed"></i>Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'register' %}"><i class="bi bi-person"></i>Register</a>
                            <a class="nav-link" href="{% url 'login' %}"><i class="bi bi-door-open"></i>Login</a>
                        {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div id="content" class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    {% block footer %}
    {% endblock %}
</body>
</html>

main/templates/main/create.html
{% extends 'main/base.html' %}

{% block title %}
Home
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <form action="{% url 'create' %}"  method="POST" class="form-group">
        {% csrf_token %}
        {{ recipe_form|crispy}}
        <table style="display: none">
            {{ ingredient_formset.management_form }}
            {{ ingredient_formset|crispy }}
        </table>
        <button type="submit" name="save" class="btn btn-success">Submit</button>
    </form>
{% endblock %}

{% block footer %}
<script>
    // function for default select2
    $(document).ready(function () {
        $('#id_diet').attr('multiple', 'multiple');
        $('#id_diet').select2({tags: true});
        $('#id_cuisine').select2({tags: true});
        $('#id_difficulty').select2({minimumResultsForSearch: Infinity});
        $('#id_cook_time').select2({minimumResultsForSearch: Infinity});
        $("select[name$='quantity_unit'").select2({tags: true});
        $("select[name$='prep_method'").select2({tags: true});
    })
    // function for ajax select2
    $(document).ready(function () {
        $('#id_recipe_ingredients-0-ingredient').select2({
            ajax: {
                url: "{% url 'create' %}",
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {id: item.id, text: item.ingredient_name};
                        })
                    };
                }
            },
            tags: true,
            minimumInputLength: 1
        });
        $('select').blur(function() {
            $.ajax({
                type: "POST",
                url: "{% url 'create' %}",
                data: {
                    field_value: $(this).val()
                },
                success: function(new_val) {
                    // logic for setting element value
                }
            })
        })
    });
    // function to add new item to database when created
</script>
{% endblock %}

main/templates/main/edit.html
{% extends 'main/base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
{% endblock %}

main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
{% endblock %}

main/templates/main/recipe_page.html
{% extends 'main/base.html' %}

{% block title %}
Recipe Page
{% endblock %}

{% block content %}
{% endblock %}

main/templates/main/recipie_page.html
{% extends 'main/base.html' %}

{% block title %}
Recipie Page
{% endblock %}

{% block content %}
{% endblock %}

main/templates/main/user_home.html
{% extends 'main/base.html' %}

{% block title %}
Your Home
{% endblock %}

{% block content %}
{% endblock %}